name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  BUILD_TARGET: x86_64-unknown-linux-musl
  BINARY_NAME: helmci

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: Fmt Check
        run: cargo fmt -- --check
      - name: Clippy
        run: cargo clippy --no-deps -- -Dwarnings
      - name: Compile
        run: cargo build
      - name: Test
        run: cargo test

  push:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner != 'electronicarts' || github.event_name == 'push' }}
    needs:
      - test

    steps:
      - uses: actions/checkout@v2
      - name: Build-musl
        uses: gmiam/rust-musl-action@master
        with:
          args: cargo build --target $BUILD_TARGET --release
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BINARY_NAME }}
          path: target/x86_64-unknown-linux-musl/release/${{ env.BINARY_NAME }}*
